### ISSUE TITLE
error at curl::curl_download()

### ISSUE THREAD

**Issue by k-doering-NOAA** [ropensci-org/gitcellar#6]
Thanks for putting this package together and making it generalized!

I tried using `gitcellar::download_organization_repos` on 2 different github organizations (`r4ss` and `ss3sim`) and both errored out at `curl::curl_download(...)`. https://github.com/ropensci-org/gitcellar/blob/6639f1a56d15df007b8748bab2cd4754b3d282a7/R/repo.R#L37

It looks like `headers$location` a few lines above is `NULL` (i.e., I don't see it when calling `names(headers)` when a `browser()` statement is inserted just above `curl::curl_download(...)`and therefore causing the issue. I'm not really sure where to go next to solve the issue, though... not sure if I am doing something wrong or if this is a bug (or something specific about the orgs I tried?)?

I do have admin permissions on both of these (and got a nice warning on another org that I don't have admin permissions on), so I don't think it is related to a permissions issue?

Any help would be appreciated!

**Comment by maelle** [comment]
:wave: @k-doering-NOAA! Thanks for the bug report! It's actually a documentation problem, I'm so sorry.

I get this error actually when missing a step in my setup:

```r
Erreur dans curl::curl_download(final_url, file.path(archive_folder, sprintf("%s_%s_migration_archive.tar.gz",  : 
  Argument 'url' must be string.
```

When I do not set a GITHUB_PAT via `Sys.setenv()` first. The reason is this line https://github.com/ropensci-org/gitcellar/blob/6639f1a56d15df007b8748bab2cd4754b3d282a7/R/repo.R#L27

I'll open a PR to clarify this.

**Comment by maelle** [comment]
I can probably also improve the code, actually!

**Comment by maelle** [comment]
The code in the PR means one does NOT need to add an environment variable. Much smoother :sweat_smile:
